services:
  web:
    container_name: nginx
    build: ./nginx
    mem_reservation: 512M
    environment:
      # Dockerfile env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NGINX_VERSION=1.29.0
      - PKG_RELEASE=1
      - DYNPKG_RELEASE=1
      - NJS_VERSION=0.9.0
      - NJS_RELEASE=1
    ports:
      - 443:80

  backend:
    container_name: backend
    build: ./flask
    mem_reservation: 1024M
    environment:
      - FLASK_SERVER_PORT=9091
      - MONGO_SERVER_URL=mongo.internal:27017
      # Dockerfile env
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app
      - LANG=C.UTF-8
      - GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305
      - PYTHON_VERSION=3.12.11
      - PYTHON_SHA256=c30bb24b7f1e9a19b11b55a546434f74e739bb4c271a3e3a80ff4380d49f7adb

  mongo:
    container_name: mongo
    image: mongo:6.0
    mem_reservation: 1024M
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver_opts:
      size: 1G
